### ISSUE TITLE
Query Example

### ISSUE THREAD

**Issue by jakebresnehan** [berkansivri/DarkSky-GraphQL#1]
Any chance of providing an example query for `forecast` that I can use within the playground?

New to GraphQL and having a few issues getting it to load results.

**Comment by berkansivri** [comment]
Hi @jakebresnehan , sorry for late.
You can checkout my another repository which is consume this GraphQL server on Vue.
https://github.com/berkansivri/Vue-Weather

If you do not have any Vue experience there is a simple query example.

```
query {
  forecast(latitude: 41.008240, longitude: 28.978359) {
    timezone
    daily {
      data {
        temperatureMin
        temperatureMax
        summary
      }
    }
  }
}

```
